### ISSUE TITLE
🐛 Bug Report: Scrollbar shows as white in dark mode

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/console#1073]
### 👟 Reproduction steps

1. change the height of the window to be smaller than the content

### 👍 Expected behavior

A scrollbar appears that is dark

### 👎 Actual Behavior

A scrollbar appears that is light:

<img width="1409" alt="image" src="https://github.com/appwrite/console/assets/1477010/5d74407d-3a8c-461c-899f-517fe7fd382c">

A community member, Sujata, as suggested to add something like:

```css
::-webkit-scrollbar {
  width: 6px;
}

::-webkit-scrollbar-track {
  background: #161b22;
}

::-webkit-scrollbar-thumb {
  background: #969ba5;
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS 12.6.7 and Chrome 124.0.6367.119

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)
